### ISSUE TITLE
Upgrading Synapse from 1.37 to 1.38 appears to break matrix-eno-bot

### ISSUE THREAD

**Issue by eTomte** [8go/matrix-eno-bot#25]
I upgraded Synapse from 1.37 to 1.38 this morning, and now matrix-eno-bot will no longer start up.

I believe there were some DB changes as part of the 1.38 update...perhaps this is what broke the bot.

**Comment by toushin-taishi** [comment]
Yes, I noticed this as well. Upgrading to synapse 1.38 broke matrix-eno-bot or the matrix-nio client library.

**Comment by eTomte** [comment]
Thanks!  That fixed it for me too.

**Comment by 8go** [comment]
Thanks to both @eTomte and @toushin-taishi for reporting problem and for also finding and reporting the solution to help others!

:clap:  :heart:
