### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by KeenMaron** [8go/matrix-eno-bot#31]
Hi,

i tried to create docker package with

docker build -t matrix-eno-bot --rm .
It fails with 

"
Step 5/13 : COPY *.yaml /bot/
COPY failed: no source files were specified
"

Any advice?

**Comment by 8go** [comment]
Have a look at `commands.yaml.example`. You must copy this file to `commands.yaml` and edit it to adjust to your needs. Then try again.

**Comment by 8go** [comment]
Same of course with file `config.yaml.example`. Copy it to `config.yaml`, edit it to adjust to your environment, then try docker again.
