### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by Dual-0** [8go/matrix-eno-bot#36]
I updated my server instances to Ubuntu 24.04 (noble) wich comes with python 3.12.
With python 3.12 I get this deprecation warning:
`main.py:169: DeprecationWarning: There is no current event loop asyncio.get_event_loop().run_until_complete(main())`

The warning encountering is due to a change in Python 3.10+, where `asyncio.get_event_loop()` no longer creates a new event loop if one doesn't already exist. Instead, we should use the `asyncio.run()` function to run the main coroutine.

**Comment by 8go** [comment]
Thank you @Dual-0   :clap:

Fixed in e18c5cc2bbced2229f661a3b9a8bc022e2a7d808
