### ISSUE TITLE
Missing dependencies for virtualenv

### ISSUE THREAD

**Issue by atomtm** [8go/matrix-eno-bot#4]
Having this setup with virtualenv I had to additionally install :
```
pip install image python-magic
```

**Comment by 8go** [comment]
Thanks @atomtm for sharing. Thanks for the improvement suggestion. It is appreciated.
@apiraino kindly already fixed this for us in his PR #2 
Have a look at the `requirements.txt` file.
Thanks @atomtm , thanks @apiraino
