### ISSUE TITLE
Error when building docker image (command "COPY *.cfg /bot/" fails)

### ISSUE THREAD

**Issue by Zutart** [8go/matrix-eno-bot#7]
I'm attempting to build the docker image so that I can integrate the bot into my existing compose architecture on Ubuntu 18.04.5.

When I run the docker build command

docker build -t matrix-eno-bot --rm .

I am able to get through until Step 5:

Step 5/13 : COPY *.cfg /bot/
COPY failed: no source files were specified

**Comment by 8go** [comment]
Configure the 2 .yaml files first, then copy the *.yaml files. 
There are no .cfg files, that was a mistake. 
See commit fbba735

Good luck @Zutart

**Comment by 8go** [comment]
Looks solved. I am closing this issue. Re-open if need be.
